sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  on_failure: change
node_js:
  - stable
before_script:
  - npm prune
script: PUBLIC_PATH=/big-brain-tower npm run build
after_success:
  - bash ./deploy-gh-pages.sh
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"